#!/bin/bash

export STATELINE_SOURCE_DIR=$(pwd)

# Determine platform specific variables
if [ "$(uname)" == "Darwin" ]; then
  echo "Detected Mac OS X. Using Clang..."
  N_PROCESSORS="$(sysctl -n hw.ncpu)"
  B2_EXTRA_FLAGS='toolset=clang cxxflags="-stdlib=libc++" linkflags="-stdlib=libc++" '
else
  echo "Detected Linux. Using GCC..."
  N_PROCESSORS="$(nproc)"
  B2_EXTRA_FLAGS='toolset=gcc'
fi

printf "Using %d cores to build.\n" "$N_PROCESSORS"

# Create a prereqs folder if no prefix is specified
if [ $# -eq 0 ]; then
  mkdir -p build/prereqs
  cd build/prereqs
fi

# Create folders for the dependencies
mkdir -p src
mkdir -p include
mkdir -p lib
mkdir -p bin
cd src

#######################################
# Boost 1.59
#######################################

wget -c http://downloads.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.gz
[ -d boost_1_59_0 ] || tar -xvf boost_1_59_0.tar.gz
cd boost_1_59_0
./bootstrap.sh
./b2 -j $N_PROCESSORS --layout=versioned variant=debug,release threading=multi runtime-link=static link=static address-model=64 $B2_EXTRA_FLAGS install --prefix=$PREREQ_DIR
cd ..

#######################################
# Eigen 3.2.0
#######################################

wget -c http://bitbucket.org/eigen/eigen/get/3.2.0.tar.gz -O eigen_3.2.0.tar.gz
[ -d eigen-eigen-ffa86ffb5570 ] || tar -xvf eigen_3.2.0.tar.gz
cd eigen-eigen-ffa86ffb5570
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$PREREQ_DIR
make install
cd ../..

#######################################
# google-test (gtest) 1.7.0
#######################################

wget -c http://googletest.googlecode.com/files/gtest-1.7.0.zip
[ -d gtest-1.7.0 ] || unzip -o gtest-1.7.0.zip

#######################################
# zeromq 4.0.3
#######################################

wget -c http://download.zeromq.org/zeromq-4.0.3.tar.gz
[ -d zeromq-4.0.3 ] || tar -xvf zeromq-4.0.3.tar.gz
cd zeromq-4.0.3
./configure --prefix=$PREREQ_DIR
make -j $N_PROCESSORS
make install
cd ..

#######################################
# cppzeromq 2358037407 (commit hash)
#######################################

wget -c https://github.com/zeromq/cppzmq/archive/master.zip -O cppzmq-master.zip
[ -d cppzmq-master ] || unzip -o cppzmq-master.zip
cp cppzmq-master/zmq.hpp $PREREQ_DIR/include

#######################################
# json
#######################################

wget -c https://github.com/nlohmann/json/archive/master.zip -O json-master.zip
[ -d json-master ] || unzip -o json-master.zip
cp json-master/src/json.hpp $PREREQ_DIR/include
